//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public Nullable<int> Id { get; set; }
        public string Surname { get; set; }
        public string Middlename { get; set; }
        public string Name { get; set; }
        public Nullable<int> Pasport_serial { get; set; }
        public Nullable<int> Pasport_number { get; set; }
        public string Adress { get; set; }
        public string adress_life { get; set; }
        public string company { get; set; }
        public string jobname { get; set; }
        public string mobilephone { get; set; }
        public string email { get; set; }
        public byte[] photo { get; set; }
        public string description { get; set; }
    }
}
